
# STAGE 1: Build stage --------------------------------

# Light weight image of python 3.8
FROM python:3.8-slim AS build

# Setup working directory for the following commands
WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libmariadb-dev \
    pkg-config

COPY . .

RUN pip install flask mysqlclient


# STAGE 2: Prod stage --------------------------------

FROM python:3.8-slim

WORKDIR /app

COPY --from=build /app /app 
COPY --from=build /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends libmariadb3 \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 5002

# Start container app
CMD ["python", "app.py"]