version: "3.8"

services:
  web:
    image: 741010684692.dkr.ecr.eu-north-1.amazonaws.com/hello-flask-app:latest
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
