events { worker_connections 1024; } # Max number of simultaneous connections that can be opened by a worker process

http { # HTTP conf block where web traffic rules are defined
    upstream flask_app { # Defines a group of backend servers that Nginx can proxy requests to
        # 'web' matches the service name in docker-compose.yml
        server web:5001;
    }

    server { # Virtual server conf block
        listen 80; # Nginx listens on port 80 for incoming HTTP requests

        location / { # Routing block that catches every incoming URL request starting with a forward slash (everything).
            proxy_pass http://flask_app; # Acts as a reverse proxy. Fwds incoming requests to the upstream group defined above (flask_app)

            # The following three lines are important for passing along the original request information to the backend server (Flask app). 
            # Without these, the Flask app may not have accurate information about the original request.
            proxy_set_header Host $host; # Pass the original Host header from the client to the backend server
            proxy_set_header X-Real-IP $remote_addr; # Passes the user's exact IP address to Flask so your app knows who sent the request.
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Keeps track of a list of proxy server IPs the request passed through, appending the user's IP.
        }
    }
}